# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freefolks', '0008_auto_20180603_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpiling',
            name='grand_taken',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name=b'Stockpile amount taken'),
        ),
        migrations.AlterField(
            model_name='stockpiling',
            name='stockpile_number',
            field=models.IntegerField(choices=[(1, b'stockpile_1'), (2, b'stockpile_2'), (3, b'stockpile_3'), (4, b'stockpile_4'), (5, b'stockpile_5'), (6, b'stockpile_6'), (7, b'stockpile_7'), (8, b'stockpile_8'), (9, b'stockpile_9'), (10, b'stockpile_10'), (11, b'stockpile_11'), (12, b'stockpile_12'), (13, b'stockpile_13'), (14, b'stockpile_14'), (15, b'stockpile_15'), (16, b'stockpile_16'), (17, b'stockpile_17'), (18, b'stockpile_18'), (19, b'stockpile_19'), (20, b'stockpile_20')], verbose_name=b'Stockpile number'),
        ),
    ]
