# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_clue'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
