# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_clue_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='slug',
            field=models.SlugField(),
        ),
    ]
