# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180721_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
