# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_clue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='title',
            field=models.CharField(max_length=200, verbose_name=b'Title'),
        ),
    ]
