# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180722_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='short',
            field=models.TextField(default='sample short story', max_length=200, verbose_name=b'Short Story'),
            preserve_default=False,
        ),
    ]
