# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180722_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
